name: Build

on: [push]

env:
  DOCKER_IMAGE_NAME: fossapps/micro.starter
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.203

      - name: Build
        run:  dotnet build --configuration Release

  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.203

      - name: Run Unit Tests
        run:  dotnet test

  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build Docker Image
        run: |
          TAG=`git rev-parse --short=4 ${GITHUB_SHA}`
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKERHUB_LOGIN }}" --password-stdin
          docker build . -t $DOCKER_IMAGE_NAME --build-arg VERSION=$TAG
          docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:$TAG
          docker push $DOCKER_IMAGE_NAME:$TAG

  publish:
    needs: [ build-docker-image, run-unit-tests, build ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DOCKERHUB_LOGIN: ${{secrets.DOCKERHUB_LOGIN}}
          DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        with:
          extra_plugins: |
            @semantic-release/git@7.0.18
            @semantic-release/exec@3.3.8
            @semantic-release/changelog@3.0.0
